---
- name: Update various Linux distributions
  hosts: all
  tasks:
#    - name: Upgrade installed packages on Crystal Linux
#      command: ame
#      when: ansible_hostname == "crystal"

    - name: Upgrade installed packages on Ubuntu and Debian
      become: true
      apt:
        autoremove: yes
        update_cache: yes
        upgrade: yes
        state: latest
      when:  ansible_os_family == "Ubuntu" or  ansible_os_family == "Debian"

    - name: Upgrade installed packages on Arch
      become: true
      pacman:
        update_cache: yes
        upgrade: yes
      when:  ansible_os_family == "Archlinux"

    - name: Upgrade installed packages on Rhino Linux
      command: rpk update -y
      when: ansible_hostname == "NZXT-Rhino"

    - name: Update all Snap packages
      command: snap refresh

    - name: Update all Flatpak packages
      command: flatpak update --noninteractive

    - name: check if system reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot system if required
      reboot:
      when: reboot_required.stat.exists ==  true
